openapi: 3.0.0
info:
  title: Blog API
  description: API for managing blog posts
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /posts:
    get:
      summary: Retrieves a list of all blog posts
      description: Returns a list of blog posts
      operationId: getPosts
      tags:
        - Posts
      responses:
        '200':
          description: A JSON array of blog post objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Creates a new blog post
      description: Adds a new blog post
      operationId: addPost
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Post added successfully
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /posts/{postId}:
    get:
      summary: Retrieves a blog post by ID
      description: Returns a single blog post
      operationId: getPostById
      tags:
        - Posts
      parameters:
        - in: path
          name: postId
          schema:
            type: integer
          required: true
          description: ID of the post to return
      responses:
        '200':
          description: A JSON object of a blog post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Updates a blog post
      description: Updates an existing blog post
      operationId: updatePost
      tags:
        - Posts
      parameters:
        - in: path
          name: postId
          schema:
            type: integer
          required: true
          description: ID of the post to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post updated successfully
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Deletes a blog post
      description: Deletes a blog post by ID
      operationId: deletePost
      tags:
        - Posts
      parameters:
        - in: path
          name: postId
          schema:
            type: integer
          required: true
          description: ID of the post to delete
      responses:
        '204':
          description: Post deleted successfully
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Post:
      type: object
      required:
        - title
        - content
      properties:
        id:
          type: integer
          description: The unique identifier of the post
        title:
          type: string
          description: The title of the post
        content:
          type: string
          description: The content of the post
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message