components:
  schemas:
    BlogPost:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the blog post
        title:
          type: string
          description: The title of the blog post
        content:
          type: string
          description: The content of the blog post
        author:
          type: string
          description: The author of the blog post
        createdAt:
          type: string
          format: date-time
          description: The timestamp when the blog post was created
        updatedAt:
          type: string
          format: date-time
          description: The timestamp when the blog post was last updated

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message

  requestBodies:
    BlogPostRequestBody:
      description: Blog post request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BlogPost'